name: RDLabs
favicon: null
layout_spectrum: 0.03588114399462938
typography_spectrum: 0.8818810349330306
title: IoT serves the world
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.06204778840765357
  lightness: 0.8641375643201172
  saturation: 0.38450422463938594
  rhythmicContrast: 0.6098659252747893
purpose: []
